region: us-east-1

function_name: ita-office-locations
handler: service.handler
role: lambda_api
runtime: python3.8
description: Fetches domestic and international ITA office locations, builds a single JSON document, and stores it in S3

timeout: 300
memory_size: 128
